<a href="https://colab.research.google.com/github/shailavij/Keras-Functional-API-Projects/blob/master/Preprocessing_seq_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers

In [0]:
[
  ["The", "weather", "will", "be", "nice", "tomorrow"],
  ["How", "are", "you", "doing", "today"],
  ["Hello", "world", "!"]
]

[['The', 'weather', 'will', 'be', 'nice', 'tomorrow'],
 ['How', 'are', 'you', 'doing', 'today'],
 ['Hello', 'world', '!']]

In [0]:
raw_inputs = [
  [66, 13, 1, 245, 1253, 927],
  [73, 80, 3215, 552, 927],
  [311, 932, 71]
]

In [0]:
raw_inputs

[[66, 13, 1, 245, 1253, 927], [73, 80, 3215, 552, 927], [311, 932, 71]]

In [0]:
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(raw_inputs,
                                                              maxlen=6,padding='post',truncating='pre')

print(padded_inputs)

[[  66   13    1  245 1253  927]
 [  73   80 3215  552  927    0]
 [ 311  932   71    0    0    0]]


In [0]:
# Masking
#All samples have a uniform length, the model must be informed that some part of the data is actually padding and should be ignored. That mechanism is masking.

In [0]:
# Embedding_method
embedding = layers.Embedding(input_dim=5000, output_dim=16, mask_zero=True)
masked_output = embedding(padded_inputs)

print(masked_output._keras_mask)


tf.Tensor(
[[ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True False False False]], shape=(3, 6), dtype=bool)


In [0]:
# Masking expects to see (batch, sequence, features)
# Create a dummy feature dimension using expand_dims

padded_x_train= np.expand_dims(padded_inputs,-1)
padded_x_train.shape



(3, 6, 1)

In [0]:
# Create a Masking layer
# Convert numpy into tensor 
tf_x_train= tf.convert_to_tensor(padded_x_train,dtype='float32')

masking_layer =tf.keras.layers.Masking(mask_value=0.0)
masking_layer

In [0]:
masked_x_train= masking_layer(tf_x_train)
masked_x_train


<tf.Tensor: shape=(3, 6, 1), dtype=float32, numpy=
array([[[6.600e+01],
        [1.300e+01],
        [1.000e+00],
        [2.450e+02],
        [1.253e+03],
        [9.270e+02]],

       [[7.300e+01],
        [8.000e+01],
        [3.215e+03],
        [5.520e+02],
        [9.270e+02],
        [0.000e+00]],

       [[3.110e+02],
        [9.320e+02],
        [7.100e+01],
        [0.000e+00],
        [0.000e+00],
        [0.000e+00]]], dtype=float32)>

In [0]:
print(masked_x_train. _keras_mask)

tf.Tensor(
[[ True  True  True  True  True  True]
 [ True  True  True  True  True False]
 [ True  True  True False False False]], shape=(3, 6), dtype=bool)
